ansible_ssh_common_args: "-F ssh/home.config"

rke2_version: v1.34.1+rke2r1
rke2_iface: vlan100

base_domain: lab.clusterfu.co.uk
cluster_domain: "{{ base_domain }}"

cluster_issuer:
  internal: letsencrypt-staging

node_labels:
  control_plane:
    node-role.kubernetes.io/control-plane: "true"
  data_plane:
    node-role.kubernetes.io/data-plane: "true"
  tailscale:
    node-role.kubernetes.io/tailscale: "true"
  ceph:
    node-role.kubernetes.io/ceph: "true"

argocd_enabled: true
argocd_version: "9.*"

cluster_cidr_ipv4: 10.20.0.0/16
service_cidr_ipv4: 10.21.0.0/16

cilium_version: v1.18.2
cilium_cluster_id: "20"
cilium_cluster_name: home
cilium_hubble_enabled: false
cilium_operator_replicas: 2

root_app_path: clusters/home/apps/root

ceph_enabled: true

tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63313064376661346535316365343366656161396330633836373865336461666564386364663833
  6632613464663339333232313566626562373733656439620a316331636334653534633731653935
  31316139333532623130323639386635366665393035343065313730633337613439316161393966
  3631316364303734300a636135666330666438663137323662623232313631636536623639313935
  61353062343936313962366561633665326462373136623066343836353439626539383633386665
  30643737386433386661303866356361346266336133623764356437353738373635303336393337
  366434373932333337656432353863363662

argocd_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32373330373734356361313465353732346164636232623738666464393665393063323436303337
  6462636163323462643534643565306435353865656563330a346265643365643864353062326435
  39633461356364653436356163616432396431376234383162616432383639316561663866643639
  6236656134653461320a666163616166376131666463383139623431303638336233363666363335
  33353836646330643032663934366136386563666337393631333139316230333131633330623039
  32656233303939613265313664636464393539306231373764313364616639636261633039306430
  393665636436363138383065663736636462
