rke2_version: "v1.33.4+rke2r1"
rke2_iface: "eth0"

base_domain: "example.com"
cluster_domain: "example.com"

cluster_issuer: {}

argocd_enabled: true
argocd_version: "8.*"

cluster_cidr_ipv4: ""
service_cidr_ipv4: ""

cilium_enabled: true
cilium_hubble_enabled: true
cilium_version: "v1.18.0"
cilium_cluster_id: ""
cilium_cluster_name: ""
cilium_operator_replicas: 1

node_labels: {}

root_app_path: ""

ceph_enabled: false
ceph_devices: []
